label_printer = Zebra-ZPL
labels_qta = 2
label_enable = YES
db_path = /var/qc-inspector/qc_database.sqlite
pdf_dir = /var/qc-inspector/pdf
decimal_separator = .
audio_enable = YES
report_footer_text = 
audio_pass_file =
audio_fail_file =
